# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f68c8347f8c05fcfb8a54f44013274acce176180cd6c631a3dc01a41d1c3199f877feed0e31473b353eff07d9c94cae3ae03a0b5639985de523332113ab532d1

test:
  secret_key_base: d9b6196edaa9ea1be16845b221f48d2e09b529bfe811d11b6a174e55d1fffd0501fd411b224443f92ddb0d6458c7100f45de3e537eb04e4315895b9d66a18ec0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
